using System.Collections.Generic;
using System.Linq;
using FireSprinklerPlugin.SprinkSnap.Core.Models;

namespace FireSprinklerPlugin.SprinkSnap.Core;

public interface ISprinklerFamilySelector
{
    IReadOnlyList<SprinklerFamilyInfo> GetAvailableFamilies();
}

public sealed class SprinklerFamilySelector : ISprinklerFamilySelector
{
    public static IReadOnlyList<string> VikingCategories { get; } = new[]
    {
        "Attic Sprinklers",
        "Extended Coverage",
        "Institutional Sprinklers",
        "Interstitial Concealed Sprinklers",
        "Residential Sprinklers",
        "Solid Cone Spray Nozzles",
        "Standard Spray Quick Response",
        "Standard Spray Standard Response",
        "Storage CMDA",
        "Storage CMSA",
        "Storage ESFR",
        "Storage In-Rack",
        "Window HSW",
        "Window Pendent",
        "Window Sprinklers"
    };

    public IReadOnlyList<SprinklerFamilyInfo> GetAvailableFamilies()
    {
        return DefaultFamilies;
    }

    public static IReadOnlyList<SprinklerFamilyInfo> DefaultFamilies { get; } = new List<SprinklerFamilyInfo>
    {
        CreateSprinkler(
            "Viking",
            "Standard Spray Quick Response",
            "Microfast",
            "VK302",
            "VK302",
            "Standard Spray",
            "QR Pendent K5.6",
            "Pendent",
            "Quick Response",
            "Standard Coverage",
            "Non-storage",
            5.6,
            15.0,
            225.0,
            "Libraries/Viking/VK302/Viking_VK302.rfa",
            "VK302 QR Pendent K5.6",
            "https://www.vikinggroupinc.com",
            HazardClassification.LightHazard,
            HazardClassification.OrdinaryHazardGroup1,
            HazardClassification.OrdinaryHazardGroup2),
        CreateSprinkler(
            "Tyco",
            "Standard Spray Quick Response",
            "TY-FRB",
            "TY-FRB",
            "TY-FRB",
            "Standard Spray",
            "QR Pendent K5.6",
            "Pendent",
            "Quick Response",
            "Standard Coverage",
            "Non-storage",
            5.6,
            15.0,
            225.0,
            "Libraries/Tyco/TY-FRB/Tyco_TY-FRB.rfa",
            "TY-FRB QR Pendent K5.6",
            "https://www.tyco-fire.com",
            HazardClassification.LightHazard,
            HazardClassification.OrdinaryHazardGroup1,
            HazardClassification.OrdinaryHazardGroup2),
        CreateSprinkler(
            "Reliable",
            "Standard Spray Quick Response",
            "F1FR",
            "F1FR56",
            "F1FR56",
            "Standard Spray",
            "QR Pendent K5.6",
            "Pendent",
            "Quick Response",
            "Standard Coverage",
            "Non-storage",
            5.6,
            15.0,
            225.0,
            "Libraries/Reliable/F1FR56/Reliable_F1FR56.rfa",
            "F1FR56 QR Pendent K5.6",
            "https://www.reliablesprinkler.com",
            HazardClassification.LightHazard,
            HazardClassification.OrdinaryHazardGroup1,
            HazardClassification.OrdinaryHazardGroup2),
        CreateSprinkler(
            "Victaulic",
            "Standard Spray Quick Response",
            "V27",
            "V2703",
            "V2703",
            "Standard Spray",
            "QR Pendent K5.6",
            "Pendent",
            "Quick Response",
            "Standard Coverage",
            "Non-storage",
            5.6,
            15.0,
            225.0,
            "Libraries/Victaulic/V2703/Victaulic_V2703.rfa",
            "V2703 QR Pendent K5.6",
            "https://www.victaulic.com",
            HazardClassification.LightHazard,
            HazardClassification.OrdinaryHazardGroup1,
            HazardClassification.OrdinaryHazardGroup2),
        CreateSprinkler(
            "Viking",
            "Standard Spray Standard Response",
            "Micromatic",
            "VK100",
            "VK100",
            "Standard Spray",
            "SR Upright K5.6",
            "Upright",
            "Standard Response",
            "Standard Coverage",
            "Non-storage",
            5.6,
            15.0,
            130.0,
            "Libraries/Viking/VK100/Viking_VK100.rfa",
            "VK100 SR Upright K5.6",
            "https://www.vikinggroupinc.com",
            HazardClassification.OrdinaryHazardGroup1,
            HazardClassification.OrdinaryHazardGroup2,
            HazardClassification.ExtraHazardGroup1),
        CreateSprinkler(
            "Tyco",
            "Storage CMDA",
            "TY-B",
            "TY-B",
            "TY-B",
            "Storage CMDA",
            "CMDA Upright K8.0",
            "Upright",
            "Standard Response",
            "Storage",
            "CMDA",
            8.0,
            15.0,
            130.0,
            "Libraries/Tyco/TY-B/Tyco_TY-B.rfa",
            "TY-B CMDA Upright K8.0",
            "https://www.tyco-fire.com",
            HazardClassification.OrdinaryHazardGroup1,
            HazardClassification.OrdinaryHazardGroup2,
            HazardClassification.ExtraHazardGroup1),
        CreateSprinkler(
            "Viking",
            "Storage CMSA",
            "VK590",
            "VK590",
            "VK590",
            "Storage CMSA",
            "CMSA Upright K11.2",
            "Upright",
            "Standard Response",
            "Storage",
            "CMSA",
            11.2,
            12.0,
            100.0,
            "Libraries/Viking/VK590/Viking_VK590.rfa",
            "VK590 CMSA Upright K11.2",
            "https://www.vikinggroupinc.com",
            HazardClassification.ExtraHazardGroup1,
            HazardClassification.ExtraHazardGroup2),
        CreateSprinkler(
            "Reliable",
            "Storage ESFR",
            "JL",
            "JL-17",
            "JL-17",
            "Storage ESFR",
            "ESFR Pendent K16.8",
            "Pendent",
            "Fast Response",
            "Storage",
            "ESFR",
            16.8,
            12.0,
            100.0,
            "Libraries/Reliable/JL-17/Reliable_JL-17.rfa",
            "JL-17 ESFR Pendent K16.8",
            "https://www.reliablesprinkler.com",
            HazardClassification.ExtraHazardGroup1,
            HazardClassification.ExtraHazardGroup2),
        CreateSprinkler(
            "Viking",
            "Residential Sprinklers",
            "Residential",
            "VK468",
            "VK468",
            "Residential",
            "Residential Pendent K4.9",
            "Pendent",
            "Fast Response",
            "Residential",
            "Residential",
            4.9,
            16.0,
            256.0,
            "Libraries/Viking/VK468/Viking_VK468.rfa",
            "VK468 Residential Pendent K4.9",
            "https://www.vikinggroupinc.com",
            HazardClassification.LightHazard),
        CreateSprinkler(
            "Viking",
            "Window Sprinklers",
            "Window",
            "VK960",
            "VK960",
            "Window Sprinkler",
            "Window HSW K5.6",
            "Horizontal Sidewall",
            "Quick Response",
            "Window",
            "Window",
            5.6,
            8.0,
            80.0,
            "Libraries/Viking/VK960/Viking_VK960.rfa",
            "VK960 Window HSW K5.6",
            "https://www.vikinggroupinc.com",
            HazardClassification.LightHazard,
            HazardClassification.OrdinaryHazardGroup1)
    };

    private static SprinklerFamilyInfo CreateSprinkler(
        string manufacturer,
        string category,
        string series,
        string model,
        string sin,
        string sprinklerType,
        string familyName,
        string orientation,
        string responseType,
        string coverageType,
        string storageUse,
        double kFactor,
        double maxSpacingFeet,
        double maxCoverageAreaSquareFeet,
        string revitFamilyPath,
        string revitTypeName,
        string technicalDataSheetUrl,
        params string[] supportedHazards)
    {
        return new SprinklerFamilyInfo
        {
            Manufacturer = manufacturer,
            ListedFamilyId = manufacturer + ":" + model + ":" + orientation + ":K" + kFactor.ToString("0.0"),
            Category = category,
            Series = series,
            Model = model,
            Sin = sin,
            SprinklerType = sprinklerType,
            LibraryName = "Default SprinkSnap Listed Family Library",
            FamilyName = familyName,
            Orientation = orientation,
            ResponseType = responseType,
            CoverageType = coverageType,
            StorageUse = storageUse,
            KFactor = kFactor,
            MaxSpacingFeet = maxSpacingFeet,
            MaxCoverageAreaSquareFeet = maxCoverageAreaSquareFeet,
            MaxDistanceFromWallFeet = maxSpacingFeet / 2.0,
            RevitFamilyPath = revitFamilyPath,
            RevitTypeName = revitTypeName,
            TechnicalDataSheetUrl = technicalDataSheetUrl,
            TemperatureRatings = new List<string> { "155F", "200F" },
            FinishOptions = new List<string> { "Brass", "Chrome", "White" },
            SupportedHazardClassifications = supportedHazards.ToList(),
            SupportedCeilingClassifications = new List<string>
            {
                CeilingClassification.Flat,
                CeilingClassification.TBarSuspended,
                CeilingClassification.OpenStructure
            },
            ListingNotes = "Placeholder listed-family constraints. Replace with manufacturer-specific Revit family metadata before production placement."
        };
    }
}

